### ISSUE TITLE
Bad link to Github

### ISSUE THREAD

**Issue by Defragster** [nathanRamaNoodles/MusicWithoutDelay-LIbrary#8]
This example link misses the mark: https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary/blob/master/examples/Basic/Basic.ino#L31

Opened this sample and it ran well with Teensy LC - using the PJRC Prop Shield for an Amp.

Nice work!

**Comment by nathanRamaNoodles** [comment]
Alright, I fixed it and upgraded to v3.5.0 with tons of other features including stereo support
